Feature/question sorting
plus-me/frontend pull request #116
Opened 2021-08-30 18:51 UTC by ri0t

Closes #90

2021-08-30 19:21 UTC, enko requested changes
Was mir auf jeden Fall fehlt ist, das das Icon anzeigt, dass eine Sortierung eingeschalten ist. Zusätzlich sollte im Drop-Down auch ersichtlich sein, welche Sortierung aktiv ist.

Zusätzlich könnte man überlegen bei "Beantwortet"  und "Folge ich" einen Filter zu applizieren anstatt einfach nur zu sortieren (Falls das einfach umsetzbar ist).

Außerdem würde ich das Sortieren-Icon eins nach links schieben, weil das Schließen-Icon immer und überall rechts oben ist.

2021-08-31 19:37 UTC, ri0t commented
> Was mir auf jeden Fall fehlt ist, das das Icon anzeigt, dass eine Sortierung eingeschalten ist. Zusätzlich sollte im Drop-Down auch ersichtlich sein, welche Sortierung aktiv ist.

* [ ] Aber.. äh, es ist immer eine sortierung an (per default newest). 
* [x] Die aktive sortierung hab ich jetzt drin.

> Zusätzlich könnte man überlegen bei "Beantwortet" und "Folge ich" einen Filter zu applizieren anstatt einfach nur zu sortieren (Falls das einfach umsetzbar ist).

Hmm. Weiss nicht recht. Ich lass es erstmal so.

> Außerdem würde ich das Sortieren-Icon eins nach links schieben, weil das Schließen-Icon immer und überall rechts oben ist.

* [x] done

2021-09-01 19:14 UTC, enko commented
@ri0t mir ist noch ein Bug aufgefallen:

Ich mache die Suche auf und suche nach einem Begriff und sortiere nach Beliebtheit. Dann Schließe ich die Suche, klicke auf einen Tag um die Suche zu triggern und dann ist nach neustes sortiert, obwohl nach Beliebtheit im Dropdown ausgewählt ist.

Ich würde hier erwarten das immer noch nach Beliebtheit sortiert ist.

2021-09-10 19:20 UTC, enko approved these changes

2021-09-10 19:20 UTC, merged