feat: question bubble works and looks almost like figma design
plus-me/frontend pull request #27
Opened 2021-07-26 14:26 UTC by ri0t

* Die tags gehen nicht mehr. Mit dem TagsHelper gingen sie noch, mit der neuen Methode hab ich irgendwas verborkt.
* Das padding ist nicht korrekt, im Figma nimmt die Karte deutlich mehr platz und zentriert die frage im freien raum.
* Der link zum "Frage melden" muss woanders hin.

2021-07-26 15:03 UTC, enko requested changes

2021-07-26 15:03 UTC, enko commented on src/assets/lang/de.json
> +    "people_asking": "Personen fragen",
Besser hier 🐫 case, kein Grund für snake_case

2021-07-26 17:51 UTC, ri0t commented on src/assets/lang/de.json
> +    "people_asking": "Personen fragen",
snek case entfernt

2021-07-28 18:52 UTC, enko approved these changes
LGTM

2021-07-29 12:54 UTC, merged